-- MySQL Script generated by MySQL Workbench
-- Thu May 26 15:25:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema introDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema introDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `introDB` DEFAULT CHARACTER SET utf8 ;
USE `introDB` ;

-- -----------------------------------------------------
-- Table `introDB`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `introDB`.`marcas` (
  `idMarca` TINYINT(255) NOT NULL AUTO_INCREMENT,
  `mkNombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `introDB`.`categoriAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `introDB`.`categoriAS` (
  `idCategoria` TINYINT(255) NOT NULL AUTO_INCREMENT,
  `catNombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `introDB`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `introDB`.`productos` (
  `idProducto` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `prdNombre` VARCHAR(45) NOT NULL,
  `prdPrecio` FLOAT(8,2) NOT NULL,
  `idMarca` TINYINT(255) NOT NULL,
  `idCategoria` TINYINT(255) NOT NULL,
  `prdDescripcion` VARCHAR(500) NOT NULL,
  `prdImagen` VARCHAR(45) NOT NULL,
  `prdActivo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `fk_productos_marcas`
    FOREIGN KEY (`idMarca`)
    REFERENCES `introDB`.`marcas` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_categoriAS1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `introDB`.`categoriAS` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


